azure-storage-blob sdk changes
BlobService doesn't exist in  the latest version of azure-storage-blob SDK (0.36.0 )
from azure.storage.blob import BlobService  throws  ImportError: cannot import name 'BlobService' exception 
The code has been changed based on blob storage python SDK docs https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-python